openapi: 3.0.3
info: 
  title: Connected Network Type Subscriptions
  description: |
    This API provides the API consumer with the ability to subscribe to notifications on changes to the connected network type of a device.

    # Introduction

    ## Connected Network Type Subscription
    API consumers can subscribe to receive notifications when the connected network type of a device changes. These notifications are delivered through CloudEvents.

    # Relevant terms and definitions

    * **Device**: A device refers to any physical entity that can connect to a network and participate in network communication.
      At least one identifier for the device (user equipment) out of four options: IPv4 address, IPv6 address, Phone number, or Network Access Identifier (not supported for this API version) assigned by the mobile network operator for the device.

    * **Connected Network Type**: This Type identifies the mobile technology of the network that the device is connected to (e.g. 4G, 5G, etc). It is the same as what is displayed on the device (e.g. on mobile phones). When the device moves across different areas of the network, the technology may change. As each technology is different, network capabilities may differ and MUST be checked with the API provider.
       - `2G`: if device is connected to the 2G network technology (alternative indicators such as "G" or "E" may be displayed on the device)
       - `3G`: if device is connected to the 3G network technology (alternative indicators such as "H" or "H+" may be displayed on the device)
       - `4G`: if device is connected to the 4G network technology (alternative indicators such as "LTE" or "LTE+" may be displayed on the device)
       - `5G`: if device is connected to the 5G network technology
       - `UNKNOWN`: if connection [technology] can not be determined
    # API Functionality

    The API exposes following capabilities:

    ## Connected Network Type Subscription Management

    These endpoints allow you to manage subscriptions for receiving notifications on changes to the connected network type of a device.
    The CAMARA subscription model is detailed in the CAMARA API design guideline document and follows CloudEvents specification.

    It is mandatory in the subscription to provide the event `type` for which the client would like to subscribe.

    Following event ``type`` are managed for this API:
      - ``org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed``: This event is triggered when the connected network type of the device changes.

    Note: Additionally, the event `org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends` is sent when the subscription ends.
    This notification does not require dedicated subscription.

    It is used in following cases:
      - the subscription expire time (optionally set by the requester) has been reached
      - the maximum number of subscription events (optionally set by the requester) has been reached
      - the subscription was deleted by the requester
      - the Access Token `sinkCredential` (optionally set by the requester) expiration time has been reached
      - the API server has to stop sending notification prematurely

    **Note on combined usage of ``initialEvent`` and ``subscriptionMaxEvents``**:

    If an event is triggered following ``initialEvent`` set to true,
    this event will be counted towards ``subscriptionMaxEvents`` (if provided).


    **Clarification on ``initialEvent`` & ``event-type`` behaviour:**

    When ``initialEvent`` is set to ``true`` in the subscription request, a notification has to be sent immediately to provide the connected network type of the device targeted.
    Note: If the status can not be determined, or if the device is not connected, we send an inital event with ``connectedNetworkType`` valued to`UNKNOWN`.

    ### Notifications callback

    This endpoint describes the event notification received on subscription listener side when the event occurred.
    As for subscription, detailed description of the event notification is provided in the CAMARA API design guideline document.

    _**WARNING**: This callback endpoint must be exposed on the consumer side as `POST /{$request.body#/sink}`.
      Developers may provide a callback URL on which notifications regarding connected network type can be received from the service provider.
      If an event occurs the application will send events to the provided webhook - 'sink'._

    # Further info and support

    ## Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.

    ## Identifying the device from the access token

    This API requires the API consumer to identify a device as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `device` object, which therefore MUST be provided.

    - When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token.

    This approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.

    ### Error handling:
    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

    - If the subject can be identified from the access token and the optional `device` object is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same device is identified by these two methods, as the server is unable to make this comparison.

    ## Multi-SIM scenario handling

    In multi-SIM scenarios where more than one mobile device is associated with a phone number (e.g. a smartphone with an associated smartwatch), it might not be possible to uniquely identify from that phone number the device for which connected network type notifications should be generated. If the phone number is used as the device identifier when creating a subscription in a multi-SIM scenario, the API may:
    - respond with an error, or
    - generate network type change notifications for the multi-SIM group as a whole, or
    - generate network type change notifications for a single device in the multi-SIM group, which may not be the intended device.

    Possible solutions in such a scenario include:
    - Using the authorisation code flow to obtain an access token, which will automatically identify the intended device
    - Identifying the intended device from a unique identifier for that device, such as its source IP address and port
    - Check with the SIM provider whether a unique "secondary" phone number is already associated with each device, and use the secondary phone number to identify the intended device if available.

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  x-camara-commonalities: 0.5
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/DeviceStatus

paths: {}

components:
  # Vendor extension documenting entitlements for each event type
  x-camara-entitlements:
    "org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed":
      required:
        scopes: ["camara-cloudevents-subscriptions:org.camaraproject.camara-cloudevents-subscriptions.v0.common:create"]         # coarse scope, shared
        roles:  ["connected-network:notify"] # custom role claim
        authorization_details:
          - type: "cloudevents-subscription"
            service: "connected-network-type"
            actions: ["create"]
            event_types: ["network-type-changed"]
          - type: "cloudevents-subscription"
            service: "connected-network-type"
            actions: ["read"]
            event_types: ["network-type-changed"]
          - type: "cloudevents-subscription"
            service: "connected-network-type"
            actions: ["delete"]
            event_types: ["network-type-changed"]
  schemas:
    SubscriptionId:
      $ref: "CAMARA-subscriptions-openapi.yaml#/components/schemas/SubscriptionId"

    TerminationReason:
      $ref: "CAMARA-subscriptions-openapi.yaml#/components/schemas/TerminationReason"

    Device:
      $ref: "CAMARA_common.yaml#/components/schemas/Device"

    ConnectedNetworkType:
      type: string
      description: Network Type is intended to provide insight to connected network's capabilities from standards perspective. Actual network capabilities may differ based on implementation and MUST be checked with the connected network provider.
      enum:
        - 2G
        - 3G
        - 4G
        - 5G
        - UNKNOWN

    org.camaraproject.connected-network-type-subscriptions.v1.detail:
      description: The detail of the requested event subscription.
      type: object
      allOf:
        - $ref: 'CAMARA-subscriptions-openapi.yaml#/components/schemas/SubscriptionDetail'
        - type: object
          properties:
            device:
              $ref: "#/components/schemas/Device"
          required:
            - device
          additionalProperties: false

    CloudEvent:
      $ref: 'CAMARA-subscriptions-openapi.yaml#/components/schemas/CamaraExtendedCloudEventsAttribute'

    CloudEventData:
      $ref: 'CAMARA-subscriptions-openapi.yaml#/components/schemas/CamaraCloudEventData'

    org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed:
      description: event structure for network type change
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed.data"
          required:
            - data
      example:
        $ref: "#/components/examples/REQUEST_NETWORK_TYPE_CHANGED/value"

    org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed.data:
      description: Event detail structure for network type changed data events
      allOf:
        - $ref: "#/components/schemas/CloudEventData"
        - type: object
          properties:
            device:
              $ref: "#/components/schemas/Device"
            connectedNetworkType:
              $ref: "#/components/schemas/ConnectedNetworkType"
            subscriptionId:
              $ref: "#/components/schemas/SubscriptionId"
          required:
            - connectedNetworkType
            - subscriptionId
          additionalProperties: false

    org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends:
      description: event structure for event subscription ends
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends.data"
          required:
            - data
      example:
        $ref: "#/components/examples/NETWORKTYPE_SUBSCRIPTION_ENDS/value"

    org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends.data:
      description: Event detail structure for SUBSCRIPTION_ENDS event
      allOf:
        - $ref: "#/components/schemas/CloudEventData"
        - type: object
          properties:
            device:
              $ref: "#/components/schemas/Device"
            terminationReason:
              $ref: "#/components/schemas/TerminationReason"
            subscriptionId:
              $ref: "#/components/schemas/SubscriptionId"
            terminationDescription:
              type: string
              description: termination description
          required:
            - terminationReason
            - subscriptionId
          additionalProperties: false

  examples:
    REQUEST_NETWORK_TYPE_CHANGED:
      description: The cloud event when a connected network type changed
      value:
        id: "123655"
        source: https://notificationSendServer12.supertelco.com
        type: "org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed"
        specversion: "1.0"
        datacontenttype: application/json
        data:
          subscriptionId: "987654321"
          device:
            phoneNumber: "+123456789"
          connectedNetworkType: 5G
        time: "2023-03-22T05:40:23.682Z"

    NETWORKTYPE_SUBSCRIPTION_ENDS:
      value:
        id: "124003"
        source: https://dataUsageServer.supertelco.com
        type: "org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends"
        specversion: "1.0"
        datacontenttype: application/json
        data:
          device:
            phoneNumber: "+123456789"
          terminationReason: SUBSCRIPTION_EXPIRED
          subscriptionId: dv10-h556-rt89-1403
          terminationDescription: Subscription expiry time has been reached
        time: "2024-03-05T15:00:23.682Z"

    NETWORKTYPE_SUBSCRIPTION_ACTIVE:
      value:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
          - "org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed"
        config:
          subscriptionDetail:
            device:
              phoneNumber: "+123456789"
          subscriptionExpireTime: "2024-07-17T13:18:23.682Z"
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: "2024-07-03T21:12:02.871Z"
        expiresAt: "2024-07-03T21:12:02.871Z"
        status: ACTIVE

    NETWORKTYPE_CREATE_SUBSCRIPTION:
      value:
        sink: "https://endpoint.example.com/sink"
        sinkCredential: {
          "credentialType": "ACCESSTOKEN",
          "accessToken": "JhbGciOiJSUzI1NiIsImtpZCI6Imk2bEdrM0ZaenhSY1ViMkMzbkVRN3N5SEpsW",
          "accessTokenExpiresUtc": "2024-02-17T16:23:45Z",
          "accessTokenType": "bearer"
        }
        protocol: HTTP
        types: [
          "org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed"
        ]
        config: {
          "subscriptionDetail": {
            "device": {
              "phoneNumber": "+123456789",
            }
          },
          "subscriptionExpireTime": "2023-01-17T13:18:23.682Z",
          "subscriptionMaxEvents": 5,
          "initialEvent": true
        }
