openapi: 3.0.3
info:
  title: Unified CAMARA CloudEvents v0 v1 co-existence Demo
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "{apiRoot}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root, defined by the service provider, e.g. api.example.com or api.example.com/somepath

paths:
  # CAMARA Common Subscriptions
  /subscriptions:
    $ref: ./CAMARA-subscriptions-openapi.yaml#/paths/~1subscriptions
  /subscriptions/{id}:
    $ref: ./CAMARA-subscriptions-openapi.yaml#/paths/~1subscriptions~1{id}

  # Notification receiver (client exposes this)
  /camara/cloudevents/webhook/v0:
    $ref: ./notification-as-cloud-event.yaml#/paths/~1camara~1cloudevents~1webhook~1v0

  # QoD
  /sessions:
    $ref: ./quality-on-demand.yaml#/paths/~1sessions
  /sessions/{sessionId}:
    $ref: ./quality-on-demand.yaml#/paths/~1sessions~1{sessionId}
  /sessions/{sessionId}/extend:
    $ref: ./quality-on-demand.yaml#/paths/~1sessions~1{sessionId}~1extend
  /retrieve-sessions:
    $ref: ./quality-on-demand.yaml#/paths/~1retrieve-sessions

components:
  securitySchemes:
    openId:
      $ref: ./CAMARA_common.yaml#/components/securitySchemes/openId
    notificationsBearerAuth:
      $ref: ./CAMARA_common.yaml#/components/securitySchemes/notificationsBearerAuth

  schemas:
    # CAMARA subscriptions extensions
    CamaraExtendedCloudEventsAttribute:
      $ref: ./CAMARA-subscriptions-openapi.yaml#/components/schemas/CamaraExtendedCloudEventsAttribute

    # connected-network-type-subscriptions
    org.camaraproject.connected-network-type-subscriptions.v1.detail:
      $ref: ./connected-network-type-subscriptions.yaml#/components/schemas/org.camaraproject.connected-network-type-subscriptions.v1.detail
    org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed:
      $ref: ./connected-network-type-subscriptions.yaml#/components/schemas/org.camaraproject.connected-network-type-subscriptions.v1.network-type-changed
    org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends:
      $ref: ./connected-network-type-subscriptions.yaml#/components/schemas/org.camaraproject.connected-network-type-subscriptions.v1.subscription-ends

    # geofencing-subscriptions
    org.camaraproject.geofencing-subscriptions.v1.detail:
      $ref: ./geofencing-subscriptions.yaml#/components/schemas/org.camaraproject.geofencing-subscriptions.v1.detail
    org.camaraproject.geofencing-subscriptions.v1.area-left:
      $ref: ./geofencing-subscriptions.yaml#/components/schemas/org.camaraproject.geofencing-subscriptions.v1.area-left
    org.camaraproject.geofencing-subscriptions.v1.area-entered:
      $ref: ./geofencing-subscriptions.yaml#/components/schemas/org.camaraproject.geofencing-subscriptions.v1.area-entered
    org.camaraproject.geofencing-subscriptions.v1.subscription-ends:
      $ref: ./geofencing-subscriptions.yaml#/components/schemas/org.camaraproject.geofencing-subscriptions.v1.subscription-ends
    org.camaraproject.geofencing-subscriptions.v1.subscription-status:
      $ref: ./geofencing-subscriptions.yaml#/components/schemas/org.camaraproject.geofencing-subscriptions.v1.subscription-status

    # quality-on-demand-subscriptions
    org.camaraproject.quality-on-demand.v1.detail:
      $ref: ./quality-on-demand.yaml#/components/schemas/org.camaraproject.quality-on-demand.v1.detail
    org.camaraproject.quality-on-demand.v1.qos-status-changed:
      $ref: ./quality-on-demand.yaml#/components/schemas/org.camaraproject.quality-on-demand.v1.qos-status-changed

